### ISSUE TITLE
[`publick8s`] Ensure high availability of replicated services

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3719]
During an OS image update on the ARM64 node pool of `publick8s`, some of our services were down while running multiple replicas which is unexpected.

Ref. https://matrix.to/#/!JLUOInpEYmxJIYXlzs:matrix.org/$4kD8zd8ACFf66KtK2WD9elg8UPLCpIPawW1p5GcjsNM?via=libera.chat&via=gitter.im&via=matrix.org

> update-center2 is failing because of HTTP errors from https://reports.jenkins.io/

The root cause is identified: AKS runs all replicas on the same node which defeat the purpropse of replicating pods to achieve High availability.

<img width="1402" alt="Capture d’écran 2023-08-16 à 11 27 51" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/20e4bf72-9773-41c5-8af9-439b3b802333">

We have to define, for these replicated services, a set of additional specification in the charts:

- Anti affinity https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity to ensure that replicated pods are not scheduled on the same node as other
- Eventually Pod Disruption Budget: https://kubernetes.io/docs/tasks/run-application/configure-pdb/ if needed

**Comment by smerle33** [comment]
Anti affinity didn't work as expected : 
```
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - wiki
        topologyKey: "kubernetes.io/hostname"
```

both pod were restarted at the same time on the same node, no new node were spawn (arm64).

We will check around Pod Disruption Budget or checking within the intel amd pool if the antiaffinity is triggering a new node.
