### ISSUE TITLE
Export download mirrors list to a textual representation

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3832]
### Service(s)

Other

### Summary

As requested by a user in https://groups.google.com/d/msgid/jenkins-infra/eeac78de-426d-4d13-910f-39ee7672a437n%40googlegroups.com?utm_medium=email&utm_source=footer, we could provide a textual representation of the mirrors behind get.jenkins.io (DNS and IPs).

A few points about why we don't have this list "as code" today:

- `mirrorbits` is manually configured (it has no API and it stores data inside a redis instance)
- Our helm-chart does not have a sidecar/init container in charge of configuring mirrors in `mirrorbits` deployment

=> it means that extracting this list of mirror is not easy (as much as keeping it updated). @MarkEWaite proposed a nice idea though: parsing the response from https://updates.jenkins.io/latest/jenkins.war?mirrorlist and extracting dynamically the list from this.

Proposal: use https://get.jenkins.io/index.html?mirrorstats (to avoid depending on a given WAR version which can change) and run this extraction once a week.

Then, putting this list in a set of text files (txt and json for instance) in reports.jenkins.io so it would be statically served, highly available and public.

Note: This idea was suggested months ago by @lemeurherve as it could also allows us to provide more informatiosn such as our own public IPs, in the same idea as `meta`

**Comment by smerle33** [comment]
both url are not returning the same data : 
https://get.jenkins.io/index.html?mirrorstats will not git the full path but only `xmission.org`
while 
https://updates.jenkins.io/latest/jenkins.war?mirrorlist will provide `https://mirror.xmission.com/jenkins/war/2.435/jenkins.war`

we can use the keyword `jenkins` in the url to cut it without taking care of the jenkins version number ... and the targeted url is using latest : `https://updates.jenkins.io/latest/jenkins.war?mirrorlist`

**Comment by dduportal** [comment]
> both url are not returning the same data : https://get.jenkins.io/index.html?mirrorstats will not git the full path but only `xmission.org` while https://updates.jenkins.io/latest/jenkins.war?mirrorlist will provide `https://mirror.xmission.com/jenkins/war/2.435/jenkins.war`
> 
> we can use the keyword `jenkins` in the url to cut it without taking care of the jenkins version number ... and the targeted url is using latest : `https://updates.jenkins.io/latest/jenkins.war?mirrorlist`

The URL https://get.jenkins.io/index.html?mirrorstats *does* return all configured mirrors:

<img width="1008" alt="Capture d’écran 2023-12-09 à 09 44 01" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/3111a1e8-3fd7-44aa-998d-5080a92c6a7e">


```html
<table class="alt">
    <tbody><tr>
        <th>Mirror</th>
        <th>Since 00:00 UTC…</th>
        <th>Last update</th>
    </tr>
    <tr>
        <td rowspan="2">xmission.org</td>
        <td width="500" class="tooltip"><div class="bar-download" style="width: 100%;"><span class="tooltiptext">430361<br>downloads</span></div></td>
        <td rowspan="2"><span style="color:green">4 hours ago</span></td>
    </tr>
    <tr>
        <td width="500" class="tooltip"><div class="bar-bytes" style="width: 74.04096%;"><span class="tooltiptext">1.3 TB<br>transferred</span></div></td>
    </tr><tr>
        <td rowspan="2">ftp.belnet.be</td>
        <td width="500" class="tooltip"><div class="bar-download" style="width: 63.65005%;"><span class="tooltiptext">273925<br>downloads</span></div></td>
        <td rowspan="2"><span style="color:green">4 hours ago</span></td>
    </tr>
    <tr>
        <td width="500" class="tooltip"><div class="bar-bytes" style="width: 54.098618%;"><span class="tooltiptext">952.3 GB<br>transferred</span></div></td>
    </tr><tr>
        <td rowspan="2">ftp-chi.osuosl.org</td>
        <td width="500" class="tooltip"><div class="bar-download" style="width: 58.23088%;"><span class="tooltiptext">250603<br>downloads</span></div></td>
        <td rowspan="2"><span style="color:green">41 minutes ago</span></td>
    </tr>
    <tr>
        <td width="500" class="tooltip"><div class="bar-bytes" style="width: 53.91232%;"><span class="tooltiptext">949.0 GB<br>transferred</span></div></td>
    </tr><tr>
        <td rowspan="2">rwth-aachen.de</td>
        <td width="500" class="tooltip"><div class="bar-download" style="width: 55.24943%;"><span class="tooltiptext">237772<br>downloads</span></div></td>
        <td rowspan="2"><span style="color:green">4 hours ago</span></td>
    </tr>
    <tr>
        <td width="500" class="tooltip"><div class="bar-bytes" style="width: 100%;"><span class="tooltiptext">1.7 TB<br>transferred</span></div></td>
    </tr><tr>
        <td rowspan="2">ftp-nyc.osuosl.org</td>
        <td width="500" class="tooltip"><div class="bar-download" style="width: 50.474834%;"><span class="tooltiptext">217224<br>downloads</span></div></td>
        <td rowspan="2"><span style="color:green">41 minutes ago</span></td>
    </tr>
    <tr>
        <td width="500" class="tooltip"><div class="bar-bytes" style="width: 50.381126%;"><span class="tooltiptext">886.9 GB<br>transferred</span></div></td>
    </tr><tr>
        <td rowspan="2">servanamanaged.com</td>
        <td width="500" class="tooltip"><div class="bar-download" style="width: 16.618141%;"><span class="tooltiptext">71518<br>downloads</span></div></td>
        <td rowspan="2"><span style="color:green">26 minutes ago</span></td>
    </tr>
    <tr>
        <td width="500" class="tooltip"><div class="bar-bytes" style="width: 34.187313%;"><span class="tooltiptext">601.8 GB<br>transferred</span></div></td>
    </tr><tr>
        <td rowspan="2">tsinghua.edu.cn</td>
        <td width="500" class="tooltip"><div class="bar-download" style="width: 12.581995%;"><span class="tooltiptext">54148<br>downloads</span></div></td>
        <td rowspan="2"><span style="color:green">41 minutes ago</span></td>
    </tr>
    <tr>
        <td width="500" class="tooltip"><div class="bar-bytes" style="width: 31.147236%;"><span class="tooltiptext">548.3 GB<br>transferred</span></div></td>
    </tr><tr>
        <td rowspan="2">yamagata-u.ac.jp</td>
        <td width="500" class="tooltip"><div class="bar-download" style="width: 3.1933656%;"><span class="tooltiptext">13743<br>downloads</span></div></td>
        <td rowspan="2"><span style="color:green">4 hours ago</span></td>
    </tr>
    <tr>
        <td width="500" class="tooltip"><div class="bar-bytes" style="width: 26.686014%;"><span class="tooltiptext">469.8 GB<br>transferred</span></div></td>
    </tr><tr>
        <td rowspan="2">archives.jenkins.io</td>
        <td width="500" class="tooltip"><div class="bar-download" style="width: 1.7884985%;"><span class="tooltiptext">7697<br>downloads</span></div></td>
        <td rowspan="2"><span style="color:green">44 minutes ago</span></td>
    </tr>
    <tr>
        <td width="500" class="tooltip"><div class="bar-bytes" style="width: 28.549494%;"><span class="tooltiptext">502.6 GB<br>transferred</span></div></td>
    </tr>
</tbody></table>
```

**Comment by smerle33** [comment]
should be inspired by https://api.github.com/meta

**Comment by lemeurherve** [comment]
No progress yet except that the goal of this issue is to get a MVP output of this mirror list only, keeping in mind it will be expended later.

**Comment by lemeurherve** [comment]
I've updated https://github.com/jenkins-infra/infra-reports/pull/55 to retrieve for each mirror:
- Their rank (ie distance from the requester; here from our infra, not from consumers of this list)
- Their name
- Their URL
- Their country
- Their continent

It also includes an API version and a last update date.

<details><summary>Output:</summary>

```yaml
{
  "mirrors": {
    "list": [
      {
        "rank": "0",
        "name": "Belnet",
        "url": "https://ftp.belnet.be/mirror/jenkins/",
        "country": "BE",
        "continent": "EU"
      },
      {
        "rank": "1",
        "name": "rwth-aachen.de",
        "url": "https://ftp.halifax.rwth-aachen.de/jenkins/",
        "country": "DE",
        "continent": "EU"
      },
      {
        "rank": "2",
        "name": "ftp-nyc.osuosl.org",
        "url": "https://ftp-nyc.osuosl.org/pub/jenkins/",
        "country": "US",
        "continent": "NA"
      },
      {
        "rank": "3",
        "name": "ftp-chi.osuosl.org",
        "url": "https://ftp-chi.osuosl.org/pub/jenkins/",
        "country": "US",
        "continent": "NA"
      },
      {
        "rank": "4",
        "name": "xmission.org",
        "url": "https://mirror.xmission.com/jenkins/",
        "country": "US",
        "continent": "NA"
      },
      {
        "rank": "5",
        "name": "tsinghua.edu.cn",
        "url": "https://mirrors.tuna.tsinghua.edu.cn/jenkins/",
        "country": "CN",
        "continent": "AS"
      },
      {
        "rank": "6",
        "name": "yamagata-u.ac.jp",
        "url": "https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/",
        "country": "JP",
        "continent": "AS"
      },
      {
        "rank": "7",
        "name": "Servana",
        "url": "https://sg.mirror.servanamanaged.com/jenkins/",
        "country": "SG",
        "continent": "AS"
      }
    ],
    "lastUpdate": "2024-01-26T08:05:00Z",
    "apiVersion": "0.1.0"
  }
}
```

</details>

**Comment by lemeurherve** [comment]
https://github.com/jenkins-infra/infra-reports/pull/55 updated:
- Include mirror hostname IP address(es)
- Update the main infrastructure report in place

<details><summary>Current output:</summary>

```yaml
{
  "get.jenkins.io": {
    "mirrors": [
      {
        "name": "Belnet",
        "url": "https://ftp.belnet.be/mirror/jenkins/",
        "ip": [
          "193.190.198.27"
        ],
        "country": "BE",
        "continent": "EU"
      },
      {
        "name": "rwth-aachen.de",
        "url": "https://ftp.halifax.rwth-aachen.de/jenkins/",
        "ip": [
          "137.226.34.46"
        ],
        "country": "DE",
        "continent": "EU"
      },
      {
        "name": "ftp-nyc.osuosl.org",
        "url": "https://ftp-nyc.osuosl.org/pub/jenkins/",
        "ip": [
          "64.50.233.100"
        ],
        "country": "US",
        "continent": "NA"
      },
      {
        "name": "ftp-chi.osuosl.org",
        "url": "https://ftp-chi.osuosl.org/pub/jenkins/",
        "ip": [
          "64.50.236.52"
        ],
        "country": "US",
        "continent": "NA"
      },
      {
        "name": "xmission.org",
        "url": "https://mirror.xmission.com/jenkins/",
        "ip": [
          "198.60.22.13"
        ],
        "country": "US",
        "continent": "NA"
      },
      {
        "name": "tsinghua.edu.cn",
        "url": "https://mirrors.tuna.tsinghua.edu.cn/jenkins/",
        "ip": [
          "101.6.15.130"
        ],
        "country": "CN",
        "continent": "AS"
      },
      {
        "name": "yamagata-u.ac.jp",
        "url": "https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/",
        "ip": [
          "133.24.248.16",
          "133.24.248.18",
          "133.24.248.17",
          "133.24.248.19"
        ],
        "country": "JP",
        "continent": "AS"
      },
      {
        "name": "Servana",
        "url": "https://sg.mirror.servanamanaged.com/jenkins/",
        "ip": [
          "139.144.127.39"
        ],
        "country": "SG",
        "continent": "AS"
      }
    ],
    "lastUpdate": "2024-01-29T11:02:02Z",
    "version": "v1"
  }
}


```

</details>

Now, to add new service outputs to this infrastructure report in the future, we will just have to add new scripts and modify the Jenkinsfile like this:
https://github.com/jenkins-infra/infra-reports/blob/88ea32ad4a3275538b9f7e3c187dbc6c289a0979/jenkins-infra-data/Jenkinsfile#L21-L30

```diff
--- Jenkinsfile
+++ Jenkinsfile
@@ -1,10 +1,19 @@
       environment {
         VERSION = "${version}"
+        REPORT_NAME = "${reportName}"
         REPORT_PATH = "${reportPath}"
       }
       steps {
         dir('jenkins-infra-data') {
-          sh "./get-jenkins-io_mirrors.sh > ${reportName}"
+          sh '''
+          # Execute all bash scripts from ./jenkins-infra/data folder
+          for script in ./*.sh; do
+            if [ -f "$script" ]; then
+                echo "= Processing script: ${script}"
+                bash ${script} > "${REPORT_NAME}"
+            fi
+          done
+          '''
           archiveArtifacts reportName
         }
       }

```
