### ISSUE TITLE
Migrate `release.ci.jenkins.io` to arm64 (controller only)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4042]
This issue is a follow-up of #3823 which goal is to track the operations to migrate the release.ci.jenkins.io controller to a linux/arm64 system in order to decrease the operational cost.

Requirements:

- [x] Ensure there is a dedicated `arm64` nodepool only for this controller (VM and subnet isolation)
- [x] Migrate release.ci data volume from LRS to ZRS (`pvc-ed6adfb7-5a25-4315-af8a-627c4913863d`)
  - [x] to avoid timeout add those annotations in kubernetes-management/config/jenkins_release.ci.jenkins.io.yaml => Faster restart and upgrade: decrease the attach/mount times (ref. <https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#long-volume-attachmount-times>) by adding those annotations in kubernetes-management/config/jenkins_release.ci.jenkins.io.yaml: https://github.com/jenkins-infra/kubernetes-management/pull/5136

    ```yaml
    controller:
      podSecurityContextOverride:
        runAsUser: 1000
        runAsNonRoot: true
        supplementalGroups: [1000]
    ```

  - [x] Set release.ci to shutdown mode
  - [x] Set the `statefulset` to zero replicas to ensure a proper and controlled volume unmount
  - [x] create a snapshot (from UI) named `jenkins-releaseci-snapshot-<datetime>`
  - [x] create a disk from the snapshot (from UI) named `jenkins-releaseci-snap`
  - [x] create a PV with a yaml file with the above created disk : 

    <details>

    ```yaml
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      annotations:
        pv.kubernetes.io/provisioned-by: disk.csi.azure.com
      name: jenkins-releaseci-snap
    spec:
      capacity:
        storage: 64Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: managed-csi-premium-zrs-retain
      csi:
        driver: disk.csi.azure.com
        volumeHandle: jenkins-releaseci-snap
        volumeAttributes:
          fsType: ext4
    ```

    </details>

    **note** that the volumeHandle is shorten to the diskname not the full handle `volumeHandle: jenkins-releaseci-snap`

    ```shell
    kubectl apply -f  .tmp/jenkins-releaseci-pv-snap.yaml
    ```

  - [x] create a PVC

    <details>

    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: jenkins-releaseci-snap
      namespace: jenkins-infra
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 64Gi
      volumeName: jenkins-releaseci-snap
      storageClassName: managed-csi-premium-zrs-retain
    ```

    </details>

    ```shell
    kubectl apply -f  .tmp/jenkins-releaseci-pvc-snap.yaml
    ```

  - [x] Change the storage class with a datasource as per top of the file https://github.com/jenkins-infra/kubernetes-management/pull/4720/files (DO NOT MIGRATE TO ARM64 YET) - https://github.com/jenkins-infra/kubernetes-management/pull/5138
    - note: As PVC fields are mostly immutable fields we need to ensure PVC is deleted before applying. 
  - [x] Merge the PR (infra.ci will handle the migration)

- [x] Before ARM64 migration, prepare a test job to be used to check the agent spawning and to be a test indicator
  - Details: 
    - having a pipeline running a mvn -v on each kind of agent from podtemplate.d : https://github.com/jenkins-infra/release/pull/525

- [x] Once the above requirements tasks are finished, then migrate to ARM64 with the same method used for infra.ci.jenkins.io (in https://github.com/jenkins-infra/kubernetes-management/pull/4720) by adding the proper couple of `nodeSelector` and `tolerations`. https://github.com/jenkins-infra/kubernetes-management/pull/5140

----

Definition of done

- [x] the volume is a ZRS volume in the azure UI
- [x] Delete the temporarily and manually created disk volume and PVC (claim) also the azure snapshot
- [x] the pod start and is on an ARM64 node
- [x] the jenkins CI release.ci.jenkins.io is responding
- [x] trying to launch an agent from the release.ci (need to prepare a test job)
- [x] check that the build queue is being handled

_Originally posted by @smerle33 in https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-2056385986_
