### ISSUE TITLE
migrate storage from premium to standard for jenkins-infra, jenkins-weekly and jenkins-release

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4044]
### Service(s)

infra.ci.jenkins.io, release.ci.jenkins.io, weekly.ci.jenkins.io

### Summary

a checked with the metrics, standard ZRS hdd will be enough to handle the workload for those 3 controllers. 
lets try to save some money.

this will be the occasion to handle the volumes/disk with terraform and remove the Datasource annotation from the helmchart values for controllers.

We will need to create a new Storage Class (on publick8s and privatek8s).

Sidenote: we will have to handle the boostrap permissions from the terraform managed volumes.

**Comment by smerle33** [comment]
WIP (infra and release)

<img width="2359" alt="Capture d’écran 2024-04-11 à 10 56 00" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/9500ff85-92b7-47f6-af57-eca52686a77e">
<img width="2346" alt="Capture d’écran 2024-04-11 à 10 58 07" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/c7be1a57-1477-4415-9621-374db8076f7d">
<img width="2677" alt="Capture d’écran 2024-04-15 à 15 43 19" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/21f82365-48d8-49a0-a123-3263d7e9c10c">
<img width="2666" alt="Capture d’écran 2024-04-15 à 15 44 39" src="https://github.com/
<img width="2612" alt="Capture d’écran 2024-04-11 à 10 55 22" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/c4a525d1-184f-439e-ba95-5bfddf4d8723">
<img width="2391" alt="Capture d’écran 2024-04-11 à 10 55 32" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/ba6f3c4a-0885-421a-8513-98806f30d5e4">
<img width="2357" alt="Capture d’écran 2024-04-11 à 10 55 48" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/d0dd916c-a503-4ffa-a5fa-36ea6d748dbf">
jenkins-infra/helpdesk/assets/95630726/f860dc8a-f18f-4c79-87b8-2f25ade4b2aa">

**Comment by smerle33** [comment]
WIP : 

- [ ] Add a new storage class for standard ssd ZRS on private and public

WEEKLY.CI first

- [ ] take a snapshot for security
- [ ] add PV/PVC/DISK for weekly.ci with terraform
- [ ] create a temporary pod with both the new disk as RW and the Weekly disk as ReadOnly
- [ ] do a timed rsync test between disk

when time ok:
- [ ] take a new snapshot for security (remove the one done above)
- [ ] disable kubernetes-management builds
- [ ] remove the weekly statefulset
- [ ] on the temporary pod re-run the rsync (should be fast)
- [ ] change the helm values for weekly to use the new PV/PVC/Disk : persistence.existingClaim to PVC_NAME
- [ ] enable kubernetes-management builds
- [ ] merge the PR (changing the chart)
- [ ] check that the pod start with the correct PV/PVC
- [ ] remove the OLD PV/PVC/DISK (keep the snapshot for a few days)
- [ ] remove the snapshot

if all went well, redo for infra.ci/release.ci

**Comment by dduportal** [comment]
Update:

- New storage classes added on the 2 clusters in https://github.com/jenkins-infra/azure/pull/672
- weekly.ci planned to be migrated next week (Monday 29/Tuesday 30)

**Comment by dduportal** [comment]
Update: on hold until after the 15th of May 2024

**Comment by smerle33** [comment]
The aim is to be able to change the disk type without recreating everything next time. We choose to create PV/PVC/Disk from terraform instead of just the PVC for that (not following only creating the PVC should be enough: [kubernetes.io/docs/concepts/storage/persistent-volumes/#dynamic](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#dynamic)) 
The disk size can be changed on both scenarii.

**Comment by smerle33** [comment]
current state of test of the temporary migration pod:

```
Events:
    Type     Reason                  Age    From                     Message
    Normal   Scheduled               2m11s  default-scheduler        Successfully assigned jenkins-weekly/migrate-volume to aks-arm64small2-30051376-vmss00001i
    Warning  FailedAttachVolume      2m11s  attachdetach-controller  Multi-Attach error for volume "pvc-<redacted>" Volume is already used by pod(s) jenkins-weekly-0
    Normal   SuccessfulAttachVolume  119s   attachdetach-controller  AttachVolume.Attach succeeded for volume "jenkins-weekly-pv"
    Warning  FailedMount             8s     kubelet                  Unable to attach or mount volumes: unmounted volumes=[jenkins-home-source], unattached volumes=[jenkins-home-source], failed to process volumes=[] timed out waiting for the condition
    ```

**Comment by smerle33** [comment]
I tried with pod affinity: 
```
affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions: # app.kubernetes.io/instance: jenkins-weekly
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - jenkins-weekly
        topologyKey: app.kubernetes.io/instance   
```

without any luck 
```
0/8 nodes are available: 1 Insufficient cpu, 2 node(s) didn't match pod affinity rules, 2 node(s) had untolerated taint {CriticalAddonsOnly: true}, 3 node(s) didn't match P │
│ od's node affinity/selector. preemption: 0/8 nodes are available: 1 No preemption victims found for incoming pod, 7 Preemption is not helpful for scheduling..
pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) didn't match pod affinity rules
```

will try with node selector directly

**Comment by dduportal** [comment]
> I tried with pod affinity:
> 
> ```
> affinity:
>     podAffinity:
>       requiredDuringSchedulingIgnoredDuringExecution:
>       - labelSelector:
>           matchExpressions: # app.kubernetes.io/instance: jenkins-weekly
>           - key: app.kubernetes.io/instance
>             operator: In
>             values:
>             - jenkins-weekly
>         topologyKey: app.kubernetes.io/instance   
> ```
> 
> without any luck
> 
> ```
> 0/8 nodes are available: 1 Insufficient cpu, 2 node(s) didn't match pod affinity rules, 2 node(s) had untolerated taint {CriticalAddonsOnly: true}, 3 node(s) didn't match P │
> │ od's node affinity/selector. preemption: 0/8 nodes are available: 1 No preemption victims found for incoming pod, 7 Preemption is not helpful for scheduling..
> pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) didn't match pod affinity rules
> ```
> 
> will try with node selector directly

Don't forget that, in any case, you need the tolerations to schedule on `arm64` nodes such as this one (ref. https://github.com/jenkins-infra/kubernetes-management/blob/899229e1620277d3750ed261417703a073a4736d/config/jenkins_weekly.ci.jenkins.io.yaml#L29-L35) which might explains why pod affinity was necessary but not sufficient

**Comment by smerle33** [comment]
first try: 
- forcing the temporary pod on the same node as the jenkins-weekly + affinity
fail with : 
```
0/8 nodes are available: 1 Insufficient cpu, 2 node(s) had untolerated taint {CriticalAddonsOnly:
  true}, 5 node(s) didn't match Pod's node affinity/selector. preemption: 0/8 nodes are available: 1 No preemption victims found for incoming pod, 7 Preemption is not helpful for scheduling..
```
so I though that was the 1 Insufficient cpu matching the node hosting `jenkins-weekly`

second try:
- having the temporary pod pending with affinity
- delete jenkins-weekly pod to watch if it spawn a new node and start both pods on the new node

the `jenkins-weekly`pod stayed on the same node

third try: 
- having the temporary pod pending with affinity
- manually spawn a news arm node in the node pool
- delete jenkins-weekly pod to watch if both pods starts on the new node

The `jenkins-weekly` pod started on the new node: `aks-arm64small2-30051376-vmss00001p/10.245.0.13`
But the temporary pod stayed pending with : 

```
0/9 nodes are available: 2 node(s) had untolerated taint {CriticalAddonsOnly:
  true}, 3 node(s) didn't match Pod's node affinity/selector, 4 node(s) didn't
  match pod affinity rules. preemption: 0/9 nodes are available: 9 Preemption is
  not helpful for scheduling..
```

**Comment by smerle33** [comment]
New try: 

	- spawn manually a new node in armsmall nodepool
	- delete the jenkins-weekly pod to see if it start again on the new pod
	- start the temporary pod when weekly is on the new node.

**Comment by smerle33** [comment]
New try: 

	- spawn manually a new node in armsmall nodepool
	- delete the jenkins-weekly pod to see if it start again on the new pod
	- start the temporary pod when weekly is on the new node.
	
	
still the same behavior: 
```
  0/9 nodes are available: 2 node(s) had untolerated taint {CriticalAddonsOnly:
  true}, 3 node(s) didn't match Pod's node affinity/selector, 4 node(s) didn't
  match pod affinity rules. preemption: 0/9 nodes are available: 9 Preemption is
  not helpful for scheduling..
```

**Comment by smerle33** [comment]
found it affinity was WRONG topologyKey need to be `hostname`  not `instance` as it refer to the node: 

```
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - jenkins-weekly
        topologyKey: kubernetes.io/hostname
```

**Comment by smerle33** [comment]
So the process to follow is : 
- spawn a new compatible node for both pods (arm64)
- delete the `jenkins-weekly` pod and check that it re-spawn on the new node
- create the `temporary` pod that will spawn on the new node because of affinity

**Comment by smerle33** [comment]
When removing the resources request  it can be spawned on the existing node of jenkins-weekly, no need to use a brand new node 🎉 

```
  resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
```

**Comment by smerle33** [comment]
final version of the pod migration for jenkins-weekly
will rsync data 
 - from /var/jenkins_home on pvc `jenkins-weekly`
 - to /mnt/ on pvc  `jenkins-weekly-data`

```
apiVersion: v1
kind: Pod
metadata:
  name: migrate-volume
  labels:
    name: migrate-volume
  namespace: jenkins-weekly
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - image: jenkinsciinfra/packaging:latest
    name: migrate-volume-script
    command: ["rsync"]
    args: ["-a", "--delete", "/var/jenkins_home", "/mnt/"] #will create the destination folder within /mnt/
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkins-home-source
      readOnly: true
    - mountPath: /mnt
      name: jenkins-home-destination
  nodeSelector:
    kubernetes.io/arch: arm64
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "arm64"
      effect: "NoSchedule"
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - jenkins-weekly
        topologyKey: kubernetes.io/hostname
  restartPolicy: Never
  volumes:
  - name: jenkins-home-source
    persistentVolumeClaim:
      claimName: jenkins-weekly
  - name: jenkins-home-destination
    persistentVolumeClaim:
      claimName: jenkins-weekly-data
```

**Comment by smerle33** [comment]
jenkins-weekly cleanup

disk premium removed `pvc-d6f52829-b9a9-4d0e-bd38-777005a77d08`
PV removed

old snapshot `jenkins-weekly-snapshot-20240515-0907` removed
new snapshot done, to remove later

**Comment by smerle33** [comment]
migration for release.ci

- [ ] create PV/PVC/DISK for release.ci on privatek8s - https://github.com/jenkins-infra/azure/pull/768
- [ ] run migration pod to prepare new disk
- [ ] make a snapshot of old volume (premium)
- [ ] prepare release.ci for shutdown to lock new builds
- [ ] when builds all done : launch migration pod again
- [ ] merge PR of migration - https://github.com/jenkins-infra/kubernetes-management/pull/5379
- [ ] check release.ci use new PV/PVC/DISK
- [ ] cleanup old volume/PV (24h later)
- [ ] cleanup snapshot (1 week later)

**Comment by smerle33** [comment]
pod template for migration
```
apiVersion: v1
kind: Pod
metadata:
  name: migrate-volume
  labels:
    name: migrate-volume
  namespace: jenkins-release
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - image: jenkinsciinfra/packaging:latest
    name: migrate-volume-script
    command: ["rsync"]
    args: ["-v", "-a", "--delete", "/var/jenkins_home", "/mnt/"] #will create the destination folder within /mnt/
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkins-home-source
      readOnly: true
    - mountPath: /mnt
      name: jenkins-home-destination
  nodeSelector:
    kubernetes.io/arch: arm64
    kubernetes.azure.com/agentpool: releacictrl
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "arm64"
      effect: "NoSchedule"
    - key: "jenkins"
      operator: "Equal"
      value: "release.ci.jenkins.io"
      effect: "NoSchedule"
    - key: "jenkins-component"
      operator: "Equal"
      value: "controller"
      effect: "NoSchedule"
  restartPolicy: Never
  volumes:
  - name: jenkins-home-source
    persistentVolumeClaim:
      claimName: jenkins-release
  - name: jenkins-home-destination
    persistentVolumeClaim:
      claimName: jenkins-release-data
```
