### ISSUE TITLE
Change trusted.ci to use Managed Identity authentication for authenticating to Azure

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#4118]
### Service(s)

trusted.ci.jenkins.io

### Summary

It would be great to not use password credentials when they can be avoided, this can be done with Managed Identity.

----

1. Create a managed identity in Azure:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/user_assigned_identity

2. Ensure workload identity is enabled on AKS (requires 2 variables, workload_identity_enabled and oidc_issuer_enabled):
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#workload_identity_enabled
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#oidc_issuer_enabled

3. Create a service account for Jenkins to use in Kubernetes and link the service account to the identity:

https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet#service-account-annotations

4. Modify the Jenkins pod to use it:

```yaml
  values:
    controller:
      podLabels:
        azure.workload.identity/use: "true"
```

5. Create a managed identity credential in Jenkins with configuration as code:
```yaml
                      - azureImds:
                          azureEnvName: "Azure"
                          subscriptionId: "${subscription-id}"
                          description: "Jenkins Azure identity"
                          id: "jenkins-managed-identity"
                          scope: SYSTEM
```

6. Change the credential for Azure VM Agents plugin to use it
