### ISSUE TITLE
Release of `jenkins-contribution-*` GO applications fail: homebrew token not found

### ISSUE THREAD

**Issue by jmMeessen** [jenkins-infra/helpdesk#4141]
### Service(s)

GitHub

### Summary

The GoReleaser based release process updates a repository (`jenkins-infra/homebrew`) to make the new release available via HomeBrew. With the migration of the tools from "jmMeessen" to "jenkins-infra" this process doesn't work anymore.

The error message is 
```
Error: Could not create installation access token.
(...)
  [cause]: Error: Could not retrieve installation.
(...)
    [cause]: RequestError [HttpError]: Not Found
```

This process is handled by the "release" GitHub action. It sets up on-the-fly a token via a GitHub app to allow the GHA to update another repository in the Org (the "homebrew" repository) via a commit.  In this case, the failure comes the local secrets to access the app are not set.

This is the code where the token is generated ([release.yml#L19-24](https://github.com/jenkins-infra/jenkins-contribution-extractor/blob/c836288de579876ee42a90d96f6623888637a8c2/.github/workflows/release.yml#L19C1-L24C1)):
```
    - uses: tibdex/github-app-token@v2
      id: generate_homebrew_token
      with:
        app_id: ${{ secrets.HOMEBREW_APP_ID }}
        private_key: ${{ secrets.HOMEBREW_APP_PRIVKEY }}
```

and this is how the token is retrieved and used in the release step ([release.yml#L24-L31](https://github.com/jenkins-infra/jenkins-contribution-extractor/blob/c836288de579876ee42a90d96f6623888637a8c2/.github/workflows/release.yml#L24C1-L31C69)):
```
    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW: ${{ steps.generate_homebrew_token.outputs.token }}
```

As far as I remember, the solution is to install an application that has update/commit access in jenkins-infra/homebrew repository and to add the APP_ID and the APP_PRIVKEY as secrets in the repository.

**Comment by lemeurherve** [comment]
For reference, from https://github.com/jenkins-infra/helpdesk/issues/4017#issuecomment-2168175465:

> [...] the first two repositories have to be configured to let goreleaser publishings corresponding taps to https://github.com/jenkins-infra/homebrew-tap.
> 
> Like what's done in https://github.com/jenkins-infra/jenkins-version/blob/1342d2771b99c6de6afee408d4b1916c1555cab3/.goreleaser.yml#L63-L76.

**Comment by jmMeessen** [comment]
I tried it out the suggested method , expecting the GITHUB_TOKEN of `jenkins-infra` to have some unusual magic. And it didn't work.

Looking closely at the GitHub action used by `jenkins-version`, I can demonstrate that it uses the GH App technique  and Tibdex/github-app-token the same way as my program did.

```
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-token
        with:
          app_id: ${{ secrets.JENKINS_ADMIN_APP_ID }}
          private_key: ${{ secrets.JENKINS_ADMIN_APP_PRIVKEY }}
```
https://github.com/jenkins-infra/jenkins-version/blob/1342d2771b99c6de6afee408d4b1916c1555cab3/.github/workflows/release.yaml#L54C1-L58C64

The only difference is that instead of loading the temporary token in HOMEBREW (obvious name IMHO), the designer of jenkins-version loads it in GITHUB-TOKEN.

@lemeurherve maybe the used secrets name are a hint to what GH App to use (JENKINS_ADMIN_APP).

I am restoring my original code.
