### ISSUE TITLE
Cannot release a new plugin with CD even if tokens are created and automatic PR on RPU merged

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#4248]
### Service(s)

ci.jenkins.io

### Summary

Hi,

This is the failed CD with 403 status code

https://github.com/jenkinsci/commons-math3-api-plugin/actions/runs/10469413524/job/28993165349

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.2:deploy (default-deploy) on project commons-math3-api: Failed to deploy artifacts: Could not transfer artifact io.jenkins.plugins:commons-math3-api:pom:3.6.1-4.vdd4613817d74 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authorization failed for https://repo.jenkins-ci.org/releases/io/jenkins/plugins/commons-math3-api/3.6.1-4.vdd4613817d74/commons-math3-api-3.6.1-4.vdd4613817d74.pom, status: 403 Forbidden
```

Hosting request: https://github.com/jenkins-infra/repository-permissions-updater/issues/4041
RPU PR: https://github.com/jenkins-infra/repository-permissions-updater/pull/4042

Contains all what's needed

```yaml
name: "commons-math3-api"
github: &GH "jenkinsci/commons-math3-api-plugin"
paths:
- "io/jenkins/plugins/commons-math3-api"
developers:
- "jonesbusy"
cd:
  enabled: true
issues:
  - github: *GH
```

The token are created on https://github.com/jenkinsci/commons-math3-api-plugin/settings/secrets/actions

![tokens](https://github.com/user-attachments/assets/01e34a0d-4454-4eba-baef-03c170392e53)

Is there anything that I'm missing ?

Thanks
