### ISSUE TITLE
[get.jenkins.io, mirrors.updates.jenkins.io] Optimize Redis used by `mirrorbits` instances (costs, security and performances)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4259]
While working on https://github.com/jenkins-infra/helpdesk/issues/2649 and https://github.com/jenkins-infra/helpdesk/issues/4240, we realized the following facts about our Redis instances:

- Cost are ~10% of the Azure CDF monthly bill
  - get.jenkins.io instance costs $13,30 daily, as a Premium P1 (6Gb) instance (ref. https://azure.microsoft.com/en-us/pricing/details/cache/)
  - mirrors.updates.jenkins.io costs $3.31 daily, as a Standard C1 (1Gb) instance (ref. https://azure.microsoft.com/en-us/pricing/details/cache/)

- Both instances are not in a private network

- The instance used by get.jenkins.io is almost full:
  - Azure Advisor recommends increasing it to a P2 size (13 Gb) to improve performances and decrease memory fragmentation

<img width="1898" alt="Capture d’écran 2024-08-23 à 15 48 26" src="https://github.com/user-attachments/assets/c63eb438-fa91-4a73-af06-de401f713473">

<img width="1606" alt="Capture d’écran 2024-08-23 à 15 59 11" src="https://github.com/user-attachments/assets/feb7634b-067e-41f8-9737-8f5af2efb288">
<img width="409" alt="Capture d’écran 2024-08-23 à 15 59 18" src="https://github.com/user-attachments/assets/82b2da75-8a0f-43be-b347-e7d34dbfc49e">
  
  - Azure Advisor also advises to either upgrade to Enterprise Redis (instead of Premium) related to storage: we are persisting Redis data with RDB every 15 min which is a great deal of I/Os in the a blob storage container in the `prodreleasecore` storage account

- Instances are using the following memory:
  - get.jenkins.io: ~5 Gb
  - mirrors.updates.jenkins.io: ~180 Mb (should increase to 800 Mb if we add 2 other mirrors)

**Comment by dduportal** [comment]
A few options to consider:

- Using a single Redis service for both services + switching to a P2 (13 Gb) + optimizing the persistence
  - Technically possible using different Redis Databases: https://github.com/etix/mirrorbits/blob/2c92eeea2e0c5fd59bd7a2b1c7f2873b565de05c/mirrorbits.conf#L59 (we already used this directive)
  - No management
  - Improve get.jenkins.io performances by giving it more room to breathe
  - Instance privacy can be done with a subnet (delegated) or with an Azure Private Link
  - Cost change would be an increase of ~$310 monthly:
    - (no storage write price change: between $1 and $2 monthly: nothing)
    -  Instance cost would be up of ~$10 daily: (1,11*24)-(13,30+3,31), e.g. a cost increase of ~$310 monthly
  - Cons: mainly no tenant separation between the 2 mirrorbits services: both could (accidentally) trash the other database if we make a mistake in the configuration

- Using a single Redis service for both services + switching to a Standard C4 (13 Gb) + optimizing the persistence
  - Technically possible using different Redis Databases: https://github.com/etix/mirrorbits/blob/2c92eeea2e0c5fd59bd7a2b1c7f2873b565de05c/mirrorbits.conf#L59 (we already used this directive)
  - No management
  - Instance privacy can be done with only an Azure Private Link
  - Improve get.jenkins.io performances by giving it more room to breathe
  - Cost change would be a decrease of ~$124 monthly:
    -  Instance cost would be down of ~$4 daily: (0,524*24)-(13,30+3,31), e.g. a cost decrease of ~$124 monthly
  - Cons: 
    - no tenant separation between the 2 mirrorbits services: both could (accidentally) trash the other database if we make a mistake in the configuration
    -  Theoretically, lower network performances as get.jenkins.io moves from Premium ("Moderate") to Standard ("Low" in that case)
    - No more Redis persistence: it's only  cache

- Running Redis ourselves in publick8s:
  - We can use Redis Sentinel for failover
    - https://github.com/bitnami/charts/tree/main/bitnami/redis#choose-between-redis-helm-chart-and-redis-cluster-helm-chart
    - https://github.com/etix/mirrorbits/blob/v0.5.1/mirrorbits.conf#L55-L62
  - Cost change would be an increase of ~$150 monthly:
    - Switching node pool from 3 (average) `Standard_D4pds_v5` (4 vCPUs / 16 Gb / 150 SSD each) nodes to 2 (average) `Standard_D8pds_v5` (8 vCPUs / 32 Gb / 150 SSD each) means cost increase from ~$400 to ~$ 530 (e.g. + 130)
    - Additional disk Storage for persistence would be around $20 monthly
  - Instance privacy is out of the box "inside the cluster" (using an internal ClusterIP) and can be enforced with Network Policies in AKS
  - Cons: 
    - We have to manage it an keep it up to date (not the easiest one)

**Comment by dduportal** [comment]
A few metrics elements to help:

- Today, get.jenkins.io runs on a 2 vCPUS + 6 Gb Redis instance which can sustain 1,5 Gbps/s network bandwidth with ~180.000 req/s (1 Kb , without SSL)
- C4 would be a é vCPUs + 13 Gb, at 0.5 Gbps/s and 60,000 req/s (1 kb without TLS)
- P2 would be 4 vCPUS + 13 Gb at 3 Gbps/s and 350,000 req/s (1 kb without TLS)

Ref. https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-best-practices-performance#premium-tier 

![Capture d’écran 2024-08-23 à 17 42 52](https://github.com/user-attachments/assets/1f159a60-bb03-40ce-b757-adefe0621996)

**Comment by dduportal** [comment]
get.jenkins.io current consumption (for the past 30 days)

- CPU:
![Capture d’écran 2024-08-23 à 17 48 46](https://github.com/user-attachments/assets/1ca16312-b7fd-448e-9376-f2a560367ca0)

-Memory:

![Capture d’écran 2024-08-23 à 17 48 21](https://github.com/user-attachments/assets/10111816-7d17-4b30-a3dd-c95ddeb5c981)

- Cache Read (outbound bandwidth to the network):

![Capture d’écran 2024-08-23 à 17 53 56](https://github.com/user-attachments/assets/8af2049f-81d8-4e7b-a9c7-fefb9e663bab)

- Cache HIT 

![Capture d’écran 2024-08-23 à 17 54 27](https://github.com/user-attachments/assets/2e32a02e-618c-4675-9b8a-2aa3dcc2dafc)

**Comment by dduportal** [comment]
For updates.jenkins.io, the metrics are currently neglect-able because we are not using it for real

**Comment by dduportal** [comment]
I vote for setting up a C4 instance:

- Would support combining both services (performance wide)
- Cost wide: it's good enough (4$ less daily)à
- Data persistence is not a blocker:
  - If we loose (and I say IF) the data we can rebuild (from the runbook) and rescan mirrors (it's done every 5 minutes!)
  - Services would keep serving data from the fallback servers (archives.jio and us-east R2 cloudflare)

Additionally, if the performance is not good enough we can increase the instance (without recreating it) to a P2 (same memory but more CPU and vnet)

**Comment by dduportal** [comment]
Additional thought @timja @MarkEWaite ?

**Comment by timja** [comment]
Any reason this isn't moved to the sponsored subscription and then you could keep using the premium without the risk?

FWIW we run redis without persistence enabled and I don't remember hitting any issues with data loss but we only use it for temporary data.

**Comment by dduportal** [comment]
> Any reason this isn't moved to the sponsored subscription and then you could keep using the premium without the risk?

Good point, let's use a P2 on the sponsored subscription 👍 We'll have to be careful if credits are not renewed though next year
 
> FWIW we run redis without persistence enabled and I don't remember hitting any issues with data loss but we only use it for temporary data.

Thanks 👍 We never issue with mirrorbits either since Dec. 2019 in Azure so should be good ! 
With the P2 we don't really car, but good to know if we have to go back to C* class.

**Comment by dduportal** [comment]
Update: https://github.com/jenkins-infra/azure/pull/811 has been merged: we now have the instance fresh new created and running privately, available through an Azure private endpoint on `publick8s`

**Comment by smerle33** [comment]
update.jenkins.io mirrorbits mirrors configurations : 

```
mirrorbits add -http https://westeurope.cloudflare.jenkins.io/ -rsync rsync://updates-jenkins-io-rsyncd.updates-jenkins-io.svc.cluster.local/jenkins/ -admin-name "jenkins-infra" -admin-email "jenkins-infra@googlegroups.com" -sponsor-name "jenkins" westeurope

mirrorbits add -http https://eastamerica.cloudflare.jenkins.io/ -rsync rsync://updates-jenkins-io-rsyncd.updates-jenkins-io.svc.cluster.local/jenkins/ -admin-name "jenkins-infra" -admin-email "jenkins-infra@googlegroups.com" -sponsor-name "jenkins" eastamerica
```

<details>
  <summary>Click to see details westeurope</summary>

```yaml
Name: westeurope
HttpURL: https://westeurope.cloudflare.jenkins.io/
RsyncURL: rsync://updates-jenkins-io-rsyncd.updates-jenkins-io.svc.cluster.local/jenkins/
FtpURL: ""
SponsorName: ""
SponsorURL: ""
SponsorLogoURL: ""
AdminName: ""
AdminEmail: ""
CustomData: ""
ContinentOnly: false
CountryOnly: false
ASOnly: false
Score: 0
Latitude: 48.8691
Longitude: 2.324464
ContinentCode: EU
CountryCodes: FR
ExcludedCountryCodes: ""
ASNum: 13335
Enabled: true
AllowRedirects: null
```

</details>

<details>
  <summary>Click to see details eastamerica</summary>

```yaml
Name: eastamerica
HttpURL: https://eastamerica.cloudflare.jenkins.io/
RsyncURL: rsync://updates-jenkins-io-rsyncd.updates-jenkins-io.svc.cluster.local/jenkins/
FtpURL: ""
SponsorName: ""
SponsorURL: ""
SponsorLogoURL: ""
AdminName: ""
AdminEmail: ""
CustomData: ""
ContinentOnly: false
CountryOnly: false
ASOnly: false
Score: 0
Latitude: 35.221386
Longitude: -80.83601
ContinentCode: NA
CountryCodes: US
ExcludedCountryCodes: ""
ASNum: 13335
Enabled: true
AllowRedirects: null
```

</details>
