### ISSUE TITLE
[ci.jenkins.io] Move ACI agents to ephemeral Windows containers to AWS

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4318]
Requires https://github.com/jenkins-infra/helpdesk/issues/4319

Goal: stop running Windows container agents in ACI and use Kubernetes instead

- Need to add Windows Node Pool(s?) in the EKS cluster - https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-windows-ami.html
  - Need to use Windows 2019 for now as we use container image built on top of nanoserver 1809: https://github.com/jenkins-infra/docker-inbound-agents/blob/17c545c52b7dfb1f329fd7a02e53f1a899b27f7b/maven/jdk17/Dockerfile.nanoserver#L24
  - Taints are needed (like https://github.com/jenkins-infra/azure/blob/e81b9697e4a9cedebf10e119b6a5a112e09b651f/privatek8s.tf#L227-L230)
- Need to add pod template with tolerations
  - Like https://github.com/jenkins-infra/release/blob/52dbc24d709a4f91328b2a2dcafe2db6f006a2c9/PodTemplates.d/package-windows.yaml#L47-L55

(edit) Given we chose to use EKS with Karpenter, the following tasks are required, following what is described in https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html

- [x] The permissions `eks:kube-proxy-windows` is required in the role assigned to nodes
  - Ref. https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support (point 5.)
- [x] The VPC CNI plugin must be set up to support Windows IPAM (otherwise we'll have weird errors when trying to start pods, related to sandbox creation found and missing pod tags with VPC IPv4)
  - Ref. https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support (point 3. and 4.)
  - Terraform configuration of the addon: https://aws-ia.github.io/terraform-aws-eks-blueprints/snippets/vpc-cni-custom-networking/
  - Helm chart of the VPC-CNI add on: https://github.com/aws/eks-charts/blob/master/stable/aws-vpc-cni/README.md
- [x] Karpenter Node Pools:
  - We need both 2019 and 2022 
  - We need to adapt the disk setup to avoid habving a 20Gb `C:` and an unused 300Gb `D:`
- [x] Implement JCasc setup for Windows Kubernetes containers
- [x] Add the 4 definitions for Windows container agents (`maven-8-window/maven-windows`, `maven-11-windows`, `maven-17-windows` and `maven-21-windows`)
- [x] (Optimization) Given the size of the container images, we should to set up an ECR pull through cache (using custom naming as we control pods) to decrease agent startup time

**Comment by dduportal** [comment]
Adding this issue to the milestone:

- Triggered a bit earlier than expected to help on https://github.com/jenkins-infra/helpdesk/issues/4490
- Will use Windows Node Pool from Karpenter as per https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2600755417
  - Note: the following page might be usefull: https://github.com/aws/karpenter-provider-aws/issues/5099#issuecomment-1820242937

**Comment by dduportal** [comment]
Update: The initial EKS requirements have been implemented with success. A single Pod extracted from a local Jenkins controller with the upcoming JCasc setup definition has been tested:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label: test-ddu
  name: jnlp-maven-21-windows-test-ddu
  namespace: jenkins-agents
spec:
  containers:
  - command:
    - pwsh.exe
    - -f
    - C:/ProgramData/Jenkins/jenkins-agent.ps1
    env:
    - name: PATH
      value: C:/tools/jdk-21/bin;$PATH
    - name: JENKINS_SECRET
      value: SuperSecret
    - name: ARTIFACT_CACHING_PROXY_SERVERID
      value: http://127.0.0.1:8080/
    - name: JAVA_HOME
      value: C:/tools/jdk-21
    - name: JENKINS_DIRECT_CONNECTION
      value: ci.jenkins.io:50000
    - name: JENKINS_AGENT_WORKDIR
      value: C:/Jenkins/agent
    - name: JENKINS_JAVA_OPTS
      value: -XX:+PrintCommandLineFlags
    - name: JENKINS_JAVA_BIN
      value: C:/tools/jdk-17/bin/java
    - name: JENKINS_PROTOCOLS
      value: JNLP4-connect
    - name: JENKINS_AGENT_NAME
      value: jnlp-maven-21-windows-test-ddu
    - name: TEMP
      value: C:/Windows/Temp
    - name: TMP
      value: C:/Windows/Temp
    - name: REMOTING_OPTS
      value: -noReconnectAfter 1d
    - name: JENKINS_INSTANCE_IDENTITY
      value: Secret
    - name: JENKINS_NAME
      value: jnlp-maven-21-windows-2llr2
    image: jenkinsciinfra/inbound-agent-maven:jdk21-nanoserver@sha256:302f2003cc52011cac1b9769b983dfd1490a520d8cdca7b0519c9f26e07c3802
    # image: jenkins/inbound-agent:3283.v92c105e0f819-8-jdk17-nanoserver-ltsc2022
    imagePullPolicy: IfNotPresent
    name: jnlp
    resources:
      limits:
        cpu: "2"
        memory: 4G
      requests:
        cpu: "2"
        memory: 4G
    volumeMounts:
    - mountPath: C:/Users/Administrator/.m2/repository
      name: volume-1
    - mountPath: C:/Windows/Temp
      name: volume-0
    - mountPath: C:/Jenkins/agent
      name: workspace-volume
    workingDir: C:/Jenkins/agent
  nodeSelector:
    kubernetes.io/arch: amd64
    kubernetes.io/os: windows
  restartPolicy: Never
  serviceAccount: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: ci.jenkins.io/agents
    operator: Equal
    value: "true"
  - effect: NoSchedule
    key: ci.jenkins.io/windows-2019
    operator: Equal
    value: "true"
  volumes:
  - emptyDir:
      medium: Memory
    name: volume-0
  - emptyDir: {}
    name: volume-1
  - emptyDir: {}
    name: workspace-volume
```
