### ISSUE TITLE
[privatek8s] migrate cluster `privatek8s` from Azure (sponsored) subscription to Azure (CDF) subscription

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4690]
Let's proceed to the migration (previous migration here https://github.com/jenkins-infra/helpdesk/issues/4250)

- [x] Check network or update it - see module "private_vnet" in https://github.com/jenkins-infra/azure-net/blob/main/vnets.tf (pairing needed)
- [x] Check VPN routes, should be ok: see https://github.com/jenkins-infra/docker-openvpn/blob/57a6c0d7efa2165e2f641a337a1973373851f631/config.yaml#L6
- [x] Create the cluster with terraform. Requires 2 steps (at least)
  - [x] Create Azure cloud resources (cluster, node pools, resources groups, Entra identities, disks, storage,e tc.)
  - [x] Then the "Kubernetes resources in a secondary PR as it requires a provider to a running cluster
- [x] Validate cluster access
  - [x] From an admin machine
  - [x] From infra.ci agents
- [x] Set up the new cluster in jenkins-infra/kubernetes-management
  - [x] Add the custom crafted `kubeconfig` in the job jenkins-infra/kubernetes-management (in infra.ci)
  - [x] Set up the cluster privatek8s with just datadog [inspired by https://github.com/jenkins-infra/kubernetes-management/pull/6485/files]
- [x] Add the other "non running applications" releases
  - [x] cert-manager + acme - IMPORTANT note: we need 2 distincts PRs. 
    - [x] `cert-manager` (to install CRDs)
    - [x] `acme` (to install the `ClusterIssuer` which **requires** CRDs to be installed)
  - [x] public-nginx-ingress - https://github.com/jenkins-infra/kubernetes-management/pull/xxx
  - [x] private-nginx-ingress - https://github.com/jenkins-infra/kubernetes-management/pull/xxx
  - [x] jenkins-infra-jobs - https://github.com/jenkins-infra/kubernetes-management/pull/xxx
- [x] Create NS/SA/PVCs/PVs for infra.ci and release.ci in terraform
  - Note: named of these resources were changed: requires kubernetes-management/config/* update
- [x] jenkins-release-agents (with updated release: independant of release.ci controller release now)
- [x]  Allow the cluster `privatek8s` IPs to reach LDAP: https://github.com/jenkins-infra/kubernetes-management/commit/682e98b6ffcb227a5aa97b4efff690d3330a0660
- [x] Announce the operation for the 4 services (release, infra, rss2twitter and github comment ops)
- [x] Prior to the operation: disable `privatek8s` from kubernetes-management - https://github.com/jenkins-infra/kubernetes-management/pull/6865
- [x] Migrate infra.ci:
    - [x] (in old cluster) Put controller in "shutdown mode"
    - [x] (in old cluster) Scale to zero to close file handles and un-mount disk automatically
    - [x] take a snapshot and grab its ID
    - [x] Terraform Azure: recreate disk/PV/PVCs with the snapshot ID - https://github.com/jenkins-infra/azure/pull/1140
    - [x] unplanned: fix disk permissions - https://github.com/jenkins-infra/azure/pull/1141
    - [x] Create migration pod and copy data:
      - [x] Create migration pod which mounts both PVCs:

        <details><summary>Click to expand Pod definition</summary>
    
          ```yaml
          ---
          apiVersion: v1
          kind: Pod
          metadata:
            name: data-migration
            namespace: infra-ci-jenkins-io
          spec:
            containers:
              - name: data-migration
                image: alpine
                command:
                  - sleep
                  - infinity
                volumeMounts:
                - name: source
                  mountPath: /data/source
                - name: destination
                  mountPath: /data/destination
            volumes:
              - name: source
                persistentVolumeClaim:
                    claimName: infra-ci-jenkins-io-data-import
              - name: destination
                persistentVolumeClaim:
                    claimName: infra-ci-jenkins-io-data
          ```
          
          </details>

      - [x] Copy data using rsync/cp, and don't forget to set the permissions:

          ```bash
          apk add rsync
          rsync -av /data/source/ /data/destination
          chown -R 1000:1000 /data/destination
          ls -ld /data/destination
          ls -la /data/destination
          # Remove cache and transient data
          rm -rf /data/destination/*cache* /data/destination/plugins/* /data/destination/nodes/* /data/destination/deadlock/* /data/destination/high-load/* /data/destination/slow-requests/* 
          ```

      - [x] Delete the pod to unmount the volumes
    - [x] Migrate DNS records - https://github.com/jenkins-infra/azure-net/pull/418
    - [x] Deploy infra-ci-jenkins-io helm release: - https://github.com/jenkins-infra/kubernetes-management/pull/6865 (applied manually with no probes)
    - [x] Reapply probes: https://github.com/jenkins-infra/kubernetes-management/commit/ebe1f0fc914cc194def8d10ca9d69150861399a4
    - [x] unplanned: fix NSG rules to allow VM ephemeral agents (and cleanup infra.ci resources in sponsored subscription as it is easier to fix issues like this)
    - [x]  unplanned: update outbound IPs on other projects:
      - [x] AWS (access with SSH from infra.ci.jenkins.io agents to pkg.origin.jenkins.io VM when building docker-packaging for keyscan): https://github.com/jenkins-infra/aws/pull/570
      - [x] DigitalOcean (management of archives.jenkins.io through SSH from infra.ci.jenkins.io agents): https://github.com/jenkins-infra/digitalocean/pull/248
      - [x] AWS sponsorship (access from infra.ci.jenkins.io agents to ci.jenkins.io and all AWS-sponsored account resources for management): Automatic `updatecli`PR: https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/299

- [x] Migrate release.ci.jenkins.io:
  - [x] (in old cluster) Put controller in "shutdown mode"
  - [x] (in old cluster) Scale to zero to close file handles and un-mount disk automatically
  - [x] take a snapshot and grab its ID
  - [x] Terraform Azure: recreate disk/PV/PVCs with the snapshot ID - https://github.com/jenkins-infra/azure/pull/1143
  - [x] Create migration pod and copy data:
      - [x] Create migration pod which mounts both PVCs:

        <details><summary>Click to expand Pod definition</summary>
    
          ```yaml
          ---
          apiVersion: v1
          kind: Pod
          metadata:
            name: data-migration
            namespace: release-ci-jenkins-io
          spec:
            containers:
              - name: data-migration
                image: alpine
                command:
                  - sleep
                  - infinity
                volumeMounts:
                - name: source
                  mountPath: /data/source
                - name: destination
                  mountPath: /data/destination
            volumes:
              - name: source
                persistentVolumeClaim:
                    claimName: release-ci-jenkins-io-data-import
              - name: destination
                persistentVolumeClaim:
                    claimName: release-ci-jenkins-io-data
           ```
          
          </details>

      - [x] Copy data using rsync/cp, and don't forget to set the permissions:

          ```bash
          apk add rsync
          rsync -av /data/source/ /data/destination
          chown -R 1000:1000 /data/destination
          ls -ld /data/destination
          ls -la /data/destination
          # Remove cache and transient data
          rm -rf /data/destination/*cache* /data/destination/plugins/* /data/destination/nodes/* /data/destination/deadlock/* /data/destination/high-load/* /data/destination/slow-requests/* 
          ```

      - [x] Delete the pod to unmount the volumes
  
  - [x] Migrate DNS - https://github.com/jenkins-infra/azure-net/pull/419
  - [x] Deploy release-ci-jenkins-io helm release: - https://github.com/jenkins-infra/kubernetes-management/pull/6870
  - [x] Cleanup old resources: https://github.com/jenkins-infra/azure/pull/1144
  - [x]  unplanned: update outbounds IPs on other projects:
      - [x] AWS (access with SSH from release.ci agents to pkg.origin.jenkins.io VM when performing Jenkins releases, during the "packaging" phase): https://github.com/jenkins-infra/aws/pull/570
      - [x] DigitalOcean (access from release.ci agents to archives.jenkins.io VM when performing Jenkins releases, during the "packaging" phase through SSH): https://github.com/jenkins-infra/digitalocean/pull/248 
  - [x] Run the "test agents jobs" to check autoscaler and PVCs permissions (in progress)
    - [x] Initial validation with manual changes: pods are scheduled (e.g. controller Kubernetes permissions, Kubernetes autoscaling, network routes for inbound agents, controller JCasC setup)
    - [x] PR in jenkins-infra/release to fix svcaccount naming and infra-health-agents pipeline improvement (in progress)
    - [x] PR in jenkins-infra/azure to manage release keyvault and its allowed IPs
    - [x] New "health" validation job works as expected
   

- [x] rss2twitter (can be done on its own)
  - [x] Need to scale down to zero the old release (in `privatek8s-sponsorship`) to avoid concurrency: ` kubectl -n rss2twitter scale --replicas=0 deployment rss2twitter`
  - [x] https://github.com/jenkins-infra/kubernetes-management/pull/6871
- [x] github-comment-ops  (can be done on its own)
  - [x] Migrate the DNS for the webhooks: https://github.com/jenkins-infra/azure-net/pull/420
  - [x] Need to scale down to zero the old release (in `privatek8s-sponsorship`) to avoid concurrency: `kubectl -n github-comment-ops scale --replicas=0 deployment github-comment-ops`
  - [x] https://github.com/jenkins-infra/kubernetes-management/pull/6871

- [x] Cleanups
  - [x] in jenkins-infra/azure:
    - [x]  Remove infra.ci remnants - https://github.com/jenkins-infra/azure/pull/1126
    - [x]  Remove release.ci remnants - https://github.com/jenkins-infra/azure/pull/1144
    - [x] Remove privatek8s-sponsorship Kubernetes resources +IP locks first - https://github.com/jenkins-infra/azure/pull/1145
    - [x] Then remove all remnants of privatek8s-sponsorship - https://github.com/jenkins-infra/azure/pull/1146
  - [x] in jenkins-infra/azure-net:
    - [x] Remove vnets/subnets/RGs of privatek8s-sponsorship - https://github.com/jenkins-infra/azure-net/pull/420
  - [x] in jenkins-infra/kubernetes-management + jenkins-infra/chart-secrets: 
    - [x] https://github.com/jenkins-infra/kubernetes-management/pull/6872 
    - [x] Secrets removal for datadog: https://github.com/jenkins-infra/charts-secrets/commit/e3e3ea4e129a7185fafd67aededed2f7f9149e3b 
    - [x] Secrets removal for infra.ci: https://github.com/jenkins-infra/charts-secrets/commit/e5a8f14e26065077a703c081a025e741fab48328
  - [x] terraform states - https://github.com/jenkins-infra/terraform-states/commit/c50962f8dec2a0fb6ec1196224a9bb34cdb55646
